schemaVersion: "2.0.0"

metadataTest:
  workdir: "/home/devops"
  entrypoint: ["uid_entrypoint"]

commandTests:
  - name: "current user"
    command: "whoami"
    expectedOutput: ["devops"]

  - name: "IBM Cloud CLI installation"
    command: "ibmcloud"
    args: ["--help"]
    expectedOutput: ["NAME:\n.*ibmcloud.*"]

  - name: "IBM Cloud container-service plugin"
    command: "ibmcloud"
    args: ["plugin", "list"]
    expectedOutput: [".*container-service/kubernetes-service.*"]

  - name: "IBM Cloud container-registry plugin"
    command: "ibmcloud"
    args: ["plugin", "list"]
    expectedOutput: [".*container-registry.*"]

  - name: "Kubectl CLI installation"
    command: "kubectl"
    args: ["--help"]
    expectedOutput: ["kubectl.*"]

  - name: "Helm CLI installation"
    command: "helm"
    args: ["--help"]
    expectedOutput: ["The Kubernetes package manager.*"]

#  - name: "Kustomize CLI installation"
#    command: "kustomize"
#    args: ["--help"]
#    expectedOutput: [".*Usage:\n  kustomize.*"]

  - name: "Git installation"
    command: "git"
    args: ["--help"]
    expectedOutput: ["usage: git.*"]

  - name: "OpenShift client installation"
    command: "oc"
    args: ["--help"]
    expectedOutput: [".*OpenShift.*"]

  - name: "Podman installation"
    command: "podman"
    args: ["--help"]
    expectedOutput: [".*podman.*"]

  - name: "Buildah installation"
    command: "buildah"
    args: ["--help"]
    expectedOutput: [".*buildah.*"]

  - name: "jq installation"
    command: "jq"
    args: ["--help"]
    expectedOutput: [".*jq.*"]

  - name: "yq installation"
    command: "yq"
    args: ["--help"]
    expectedOutput: [".*yq.*"]

#  - name: "nvm installation"
#    setup: [["/bin/bash", "--init-file", "/home/devops/.bashrc-ni"]]
#    command: "nvm"
#    args: ["--help"]
#    expectedOutput: [".*Node Version Manager.*"]

#  - name: "node installation"
#    command: "node"
#    args: ["--help"]
#    expectedOutput: ["v\\d\\d[.]\\d\\d[.]\\d\n"]

#  - name: "yo installation"
#    command: "yo"
#    args: ["--help"]
#    expectedOutput: ["\\d[.]\\d[.]\\d\n"]

fileExistenceTests:
  - name: '.bluemix'
    path: '/home/devops/.bluemix'
    shouldExist: true
    permissions: 'drwxrwx---'
    uid: 1000
    gid: 0

  - name: "uid_entrypoint"
    path: "/usr/local/bin/uid_entrypoint"
    shouldExist: true
    isExecutableBy: 'any'

  - name: "passwd"
    path: "/etc/passwd"
    shouldExist: true
    permissions: '-rw-rw-r--'

  - name: "devops"
    path: "/home/devops"
    uid: 1000

#  - name: "terraform-provider-kubernetes.*"
#    path: "/home/devops/.terraform.d/plugins"
#    shouldExist: true
#
#  - name: "terraform-provider-ibm.*"
#    path: "/home/devops/.terraform.d/plugins"
#    shouldExist: true
#
#  - name: 'cluster-pull-secret-apply.sh'
#    path: '/usr/local/bin'
#    shouldExist: true
#
#  - name: 'setup-namespace-pull-secrets.sh'
#    path: '/usr/local/bin'
#    shouldExist: true
#
#  - name: 'checkPodRunning.sh'
#    path: '/usr/local/bin'
#    shouldExist: true
